#!/bin/bash
set -ex

ENVNUM=${1:-$(date +%s)}
NODECOUNT=${2:-2}
UCINSTANCE=${3:-}
CREATE_UNDERCLOUD=${4:-""}
SSH_KEY=${5:-""}
PROVISIONNET=provision-${ENVNUM}
PUBLICNET=public-${ENVNUM}
ENVFILE=env-${ENVNUM}.yaml


source /etc/nodepoolrc

if [ ! -e /opt/stack/openstack-virtual-baremetal ] ; then
    sudo git clone https://github.com/cybertron/openstack-virtual-baremetal.git /opt/stack/openstack-virtual-baremetal
    sudo chown -R $USER /opt/stack/openstack-virtual-baremetal
fi

cd /opt/stack/openstack-virtual-baremetal/

if [ -n "$SSH_KEY" ]; then
    echo "$SSH_KEY" > temp-key-$ENVNUM.pub
    KEY_NAME="tripleo-ci-key-$ENVNUM"
    openstack keypair create --public-key temp-key-$ENVNUM.pub $KEY_NAME
else
    KEY_NAME="tripleo-cd-admins"
fi

/bin/cp --remove-destination templates/env.yaml.example $ENVFILE
sed -i -e "s/bmc_image:.*/bmc_image: bmc-template/" $ENVFILE
sed -i -e "s/key_name:.*/key_name: ${KEY_NAME}/" $ENVFILE
sed -i -e "s/node_count:.*/node_count: ${NODECOUNT}/" $ENVFILE
sed -i -e "s/os_auth_url:.*/os_auth_url: ${OS_AUTH_URL//\//\/}/" $ENVFILE
sed -i -e "s/os_password:.*/os_password: $OS_PASSWORD/" $ENVFILE
sed -i -e "s/os_tenant:.*/os_tenant: $OS_TENANT_NAME/" $ENVFILE
sed -i -e "s/os_user:.*/os_user: $OS_USERNAME/" $ENVFILE
sed -i -e "s/provision_net_shared:.*/provision_net_shared: true/" $ENVFILE
sed -i -e "s/public_net_shared:.*/public_net_shared: true/" $ENVFILE
if [ -n "$CREATE_UNDERCLOUD" ]; then
    sed -i -e "s/undercloud_name:.*/undercloud_name: extra-node/" $ENVFILE
    sed -i -e "s/undercloud_flavor:.*/undercloud_flavor: m1.small/" $ENVFILE
fi

echo -e 'resource_registry:\n'  >> $ENVFILE

if [ -z "$CREATE_UNDERCLOUD" ]; then
    echo '  OS::OVB::UndercloudEnvironment: OS::Heat::None' >> $ENVFILE
fi
echo '  OS::OVB::UndercloudFloating: templates/undercloud-floating-none.yaml' >> $ENVFILE
echo '  OS::OVB::BaremetalNetworks: templates/baremetal-networks-all.yaml' >> $ENVFILE
echo '  OS::OVB::BaremetalPorts: templates/baremetal-ports-all.yaml' >> $ENVFILE


/opt/stack/openstack-virtual-baremetal/bin/deploy.py --env $ENVFILE --name baremetal_${ENVNUM} --quintupleo --id ${ENVNUM}

while ! heat stack-show baremetal_${ENVNUM} | grep CREATE_COMPLETE ; do
    sleep 10
    if heat stack-show baremetal_${ENVNUM} | grep CREATE_FAILED ; then
        echo "Failed creating OVB stack" > $TE_DATAFILE
        exit 0
    fi
done

nova interface-attach --net-id $(neutron net-show -F id -f value $PROVISIONNET) $UCINSTANCE
nova interface-attach --net-id $(neutron net-show -F id -f value $PUBLICNET) $UCINSTANCE

# This writes out the env file as env-ID.yaml while overwrites the one we have created
/opt/stack/openstack-virtual-baremetal/bin/build-nodes-json --env $ENVFILE --nodes_json ${TE_DATAFILE:-~/instackenv.json}
