---
- name: Install system packages
  become: true
  package:
    name: "{{ rpm_packages }}"
    state: present

- name: Load vars from release file and set facts needed for repo-setup
  include_tasks: load-vars.yaml

- name: Remove pip package if already installed
  become: true
  package:
    name: python3-pip
    state: absent
  when: ansible_distribution_major_version is version('8', '>')

- name: Get pip needed for tripleo-repos installation
  include_role:
    name: ensure-pip
  vars:
    ensure_pip_from_packages: false
    ensure_pip_from_upstream: true

- name: install tripleo-repos from git checkout
  shell: |
    pushd "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-repos'].src_dir }}"
    python3 setup.py install --user
    popd
  failed_when: false
  changed_when: true

- name: install tripleo-repos as superuser to be available for yum-config module
  become: true
  shell: |
    pushd "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-repos'].src_dir }}"
    python3 setup.py install
    popd
  failed_when: false
  changed_when: true
  when: use_yum_config_module is defined and use_yum_config_module|bool

- name: Include repo-setup role
  include_role:
    name: repo-setup
  vars:
    repo_setup_dir: "{{ workspace }}"
    repo_setup_use_collections: false

- name: Install python3-tripleoclient python3-virtualenv
  become: true
  package:
    name:
      - python3-virtualenv
      - python3-tripleoclient
    state: latest
