---
- hosts: all
  name: TripleO image building job pre.yaml
  tasks:

    - name: Disable EPEL repos with dnf if exists
      command: dnf config-manager --set-disabled "epel*"
      become: true
      changed_when: true
      failed_when: false
      when:
        - ansible_pkg_mgr == "dnf"

    - name: Disable EPEL repos with yum if exists
      command: yum-config-manager --disable "epel*"
      become: true
      changed_when: true
      failed_when: false
      when:
        - ansible_pkg_mgr == "yum"

    - name: Setup repos using repo-setup role and release file
      when: ansible_distribution_major_version is version(9, '>=')
      include_role:
        name: tripleo-build-jobs-repos

    - name: Include tripleo-repos
      when: ansible_distribution_major_version is version(8, '<=')
      include_role:
        name: tripleo-repos
      vars:
        override_repos: "{{ build_override_repos | default('') }}"
        tripleo_repos_repository: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-repos'].src_dir }}"

    - name: Include bindep role
      include_role:
        name: bindep
      vars:
        bindep_dir: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/python-tripleoclient'].src_dir }}"

    - name: Import pre tasks from build-images role
      include_role:
        name: oooci-build-images
        tasks_from: pre
