---
- name: Set the ci_branch fact
  include_role:
    name: build-containers
    tasks_from: set_ci_branch.yml

- name: get extra repos delorean and deps
  become: true
  shell:
    cmd: |
      dnf config-manager --add-repo {{ item }}
  loop:
    - "https://trunk.rdoproject.org/centos9-{{ ci_branch }}/{{ promote_source | default('current-tripleo') }}/delorean.repo"
    - https://trunk.rdoproject.org/centos9-{{ ci_branch }}/delorean-deps.repo
  changed_when: true

- name: Install vitualenv
  become: true
  package:
    name: python3-virtualenv
    state: latest
