---
tripleo_deps_from_package:
  - "python3-tripleoclient"

upper_constraints_items:
  - tripleo-common
  - python-tripleoclient
  - tripleo-ansible

requirements_items:
  - openstack-tripleo-common
  - python-tripleoclient
  - tripleo-ansible

source_items:
  - "file://{{ openstack_git_root }}/{% if zuul_internal is defined %}openstack-{% endif %}tripleo-common"
  - "file://{{ openstack_git_root }}/python-tripleoclient"
  - "file://{{ openstack_git_root }}/tripleo-ansible"
  - decorator

volume_mounts:
  - "/etc/pki/ca-trust:/etc/pki/ca-trust:z"
