---
# TRIPLEO-CI environment settings
cloudenv: "ibm"
undercloud_user: "{{ lookup('env','USER') }}"
non_root_user: "{{ undercloud_user }}"
workers_args: >
    -e {{ tripleo_root }}/tripleo-ci/test-environments/worker-config.yaml
    -e /usr/share/openstack-tripleo-heat-templates/environments/debug.yaml
    --overcloud-ssh-user {{ undercloud_user }}
# ara install and config
undercloud_ansible_cfg: false

toci_vxlan_networking: true
toci_vxlan_networking_multinode: true
vxlan_mtu: 1350
hostname_correction: true  # workaround restriction on toci images

mtu: "{{ vxlan_mtu }}"
undercloud_local_mtu: "{{ mtu }}"
overcloud_neutron_global_physnet_mtu: "{{ mtu }}"

ceph_use_fqdn: true

# environment settings, not TRIPLEO-CI specific
undercloud_local_interface: "br-ex"  # related to osinfra network configuration
flavor_args: ""
undercloud_conf_extras: "net_config_override = /opt/stack/new/tripleo-ci/undercloud-configs/net-config-multinode.json.template"
# Images settings
image_cache_dir_cleanup: true
# user home (working_dir default) is the base dir for all images operations
# if it's changed, nothing will work
build_image_isolated: false
build_undercloud: false

# Rely on RDO registry instead of docker.io due to rate limit
# job.build_container_images is defined in zuul as a
# direct var.  adding build_container_images as tqe
# var so that we can turn this on/off per release w/o
# changing zuul and breaking jobs via inheritance.
docker_registry_host: >-
  {% if job is defined and
  job.build_container_images is defined and
  job.build_container_images|default(false)|bool or
  build_container_images|default(false)|bool -%}
  127.0.0.1:5001
  {%- elif job.consumer_job | default(false) | bool -%}
  {{ job.registry_ip_address_branch[release] }}:5001
  {%- else -%}
  quay.rdoproject.org
  {%- endif -%}

# Container update settings
update_containers: >-
  {% if containerized_overcloud|bool or containerized_undercloud|bool -%}
  true
  {%- endif -%}

# build-test packages
artg_repos_dir: "{{ tripleo_root }}"

# disable disk cleaning before starting installation
undercloud_clean_nodes: false
# InfluxDB module settings
influxdb_only_successful_tasks: true
influxdb_measurement: job
influxdb_url: https://influxdb.review.rdoproject.org
influxdb_port: 8086
influxdb_user: tripleo_ci
influxdb_password:
influxdb_dbname: tripleo_ci
influxdb_data_file_path: "{{ artcl_collect_dir }}/influxdb_data"
influxdb_create_data_file: true
