- name: Run DLRN gate role and create repo
  hosts: undercloud
  vars:
    artg_compressed_gating_repo: "/home/jenkins/gating_repo.tar.gz"
    ansible_user: jenkins
    ansible_user_dir: /home/jenkins/
    artg_repos_dir: "{{ tripleo_root}}"

  roles:
    - build-test-packages

# Install repo on live undercloud and overcloud image
- name: Clone the gated DLRN repos and trigger rpm injection
  hosts: undercloud
  vars:
    artg_compressed_gating_repo: "/home/jenkins/gating_repo.tar.gz"
    ansible_user: jenkins
    ansible_user_dir: /home/jenkins/
  tasks:
    - stat: path="{{ artg_compressed_gating_repo }}"
      register: gating_repo_file

    - environment:
        LIBGUESTFS_BACKEND: direct
        LIBVIRT_DEFAULT_URI: 'qemu:///session'
      block:

        - name: Create the undercloud live injection script
          template:
            src: "{{ tripleo_root }}/tripleo-quickstart/roles/libvirt/setup/undercloud/templates/inject_gating_repo.sh.j2"
            dest: "{{ working_dir }}/inject_gating_repo.sh"

        - name: Copy repo file to /tmp/
          command: cp -f "{{ artg_compressed_gating_repo }}" /tmp/gating_repo.tar.gz

        - stat: path="{{ working_dir }}/overcloud-full.qcow2"
          register: overcloud_full_img

        - name: Install virt-customize if not installed
          yum: name=libguestfs-tools-c state=latest
          become: true
          when:
            - overcloud_full_img.stat.exists
            - not multinode_mode

        - name: Inject the gating repo to overcloud image on live undercloud
          command: >
            virt-customize -a {{ working_dir }}/overcloud-full.qcow2
            --upload /tmp/gating_repo.tar.gz:/tmp/gating_repo.tar.gz
            --run '{{ working_dir }}/inject_gating_repo.sh'
          when:
            - overcloud_full_img.stat.exists
            - not multinode_mode

        - name: Run gating repo on live undercloud
          shell: >
            bash {{ working_dir }}/inject_gating_repo.sh > {{ working_dir }}/inject_repo.log
          become: true
      when: gating_repo_file.stat.exists

- name: Install built packages on multinode subnodes
  hosts: overcloud
  vars:
    artg_compressed_gating_repo: "/home/jenkins/gating_repo.tar.gz"
    ansible_user: jenkins
    ansible_user_dir: /home/jenkins/
  tasks:
    - stat: path="{{ artg_compressed_gating_repo }}"
      register: gating_repo_file
      delegate_to: undercloud

    - when:
        - gating_repo_file.stat.exists
        - multinode_mode|bool
      block:
        - name: Copy repo file to /tmp/
          copy: src="{{ artg_compressed_gating_repo }}" dest=/tmp/gating_repo.tar.gz

        - name: Create the undercloud live injection script
          template:
            src: "{{ tripleo_root }}/tripleo-quickstart/roles/libvirt/setup/undercloud/templates/inject_gating_repo.sh.j2"
            dest: "/tmp/inject_gating_repo.sh"

        - name: Run gating repo on live undercloud
          shell: >
            bash /tmp/inject_gating_repo.sh > /var/log/inject_repo.log
          become: true
