---
- name: Copy files from {{ workspace }}/ on node
  no_log: true
  synchronize:
    src: '{{ workspace }}/'
    dest: '{{ zuul.executor.log_root }}'
    mode: pull
    copy_links: true
    verify_host: true
    rsync_opts:
      - --include=/*.log
      - --include=/*.sh
      - --include=/*.txt
      - --include=*/
      - --exclude=*
      - --prune-empty-dirs

- name: Copy files from /etc/yum.repos.d/ on node
  synchronize:
    src: '/etc/yum.repos.d'
    dest: '{{ zuul.executor.log_root }}'
    mode: pull
    copy_links: true
    verify_host: true
    rsync_opts:
      - --include=/**
      - --exclude=*

- name: Copy files from {{ workspace }}/ on node
  no_log: true
  synchronize:
    src: '{{ workspace }}/'
    dest: '{{ zuul.executor.log_root }}'
    mode: pull
    copy_links: true
    verify_host: true
    rsync_opts:
      - --include=/logs/**
      - --include=*/
      - --exclude=*
      - --prune-empty-dirs
