---
# TODO akahat Delete file once lp https://bugs.launchpad.net/tripleo/+bug/1956441 fixed.
- name: Install guestfs
  include_tasks: guestfs.yaml

# TODO akahat https://bugs.launchpad.net/tripleo/+bug/1956441
- name: Remove fwupd-redfish.conf file from {{ overcloud_image_customize }}
  shell: |
    virt-customize -a {{ overcloud_image_customize }} --run-command 'rm -f /usr/lib/modules-load.d/fwupd-redfish.conf'
  args:
    chdir: "{{ workspace }}"
  environment:
    LIBGUESTFS_BACKEND_SETTINGS: force_tcg
    LIBGUESTFS_BACKEND: direct
  changed_when: true
