---
# It contains RHEL9 specific tasks
- name: get extra repos delorean and deps
  become: true
  shell:
    cmd: |
      dnf config-manager --add-repo {{ item }}
  loop:
    - "https://trunk.rdoproject.org/centos9-master/{{ promote_source | default('consistent') }}/delorean.repo"
    - https://trunk.rdoproject.org/centos9-master/delorean-deps.repo
  changed_when: true

- name: Enable supported container tools version
  become: true
  shell: |
     {{ ansible_pkg_mgr }} module switch-to container-tools:latest -y;
     {{ ansible_pkg_mgr }} clean metadata

- name: Install vitualenv
  become: true
  package:
    name: python3-virtualenv
    state: latest

- name: Include tripleo-repos
  include_role:
    name: tripleo-repos
  vars:
    override_repos: "{{ buildcontainers_override_repos | default('') }}"
    tripleo_repos_repository: "{{ ansible_user_dir }}/{{ zuul.projects['opendev.org/openstack/tripleo-repos'].src_dir }}"

- name: Install python3-tripleoclient
  become: true
  package:
    name: python3-tripleoclient
    state: latest

- name: Run build containers pre tasks
  include_role:
    name: build-containers
    tasks_from: pre
