---
- hosts: all
  tasks:

    - name: Remove EPEL repository (and clean up left-over metadata)
      package:
        name: epel-release
        state: absent
      notify: yum-clean-metadata

  handlers:
    - name: yum-clean-metadata
      command: yum clean metadata
      args:
        warn: false
