---
- name: Make sure we have pip
  include_role:
    name: ensure-pip

- name: Include OS distro version specific variables
  include_vars: "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"

- name: https://bugs.launchpad.net/tripleo/+bug/1862941 install six>=1.14.0
  pip:
    name:
      - six>=1.14.0
    extra_args: --user

- name: Ensure a recent version of pip is installed
  pip:
    name: "pip>=19.1.1"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
    virtualenv_site_packages: true

- name: Install deps from upper-constraints
  when: zuul_internal is undefined
  pip:
    extra_args: "-c {{ openstack_git_root }}/requirements/upper-constraints.txt"
    requirements: "{{ openstack_git_root }}/{{ item }}/requirements.txt"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
    virtualenv_site_packages: true
  with_items: "{{ upper_constraints_items }}"

- name: Install deps from requirements
  when: zuul_internal is defined
  pip:
    requirements: "{{ openstack_git_root }}/{{ item }}/requirements.txt"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
    virtualenv_site_packages: true
  with_items: "{{ requirements_items }}"

- name: Installation from source
  pip:
    name: "{{ source_items }}"
    virtualenv: "{{ workspace }}/venv_build"
    virtualenv_command: "{{ ensure_pip_virtualenv_command }}"
    virtualenv_site_packages: true

- name: set template override
  set_fact:
    kolla_override_path: >-
      {% if zuul_internal is defined -%}
      "{{ openstack_git_root }}/openstack-tripleo-common/container-images/tripleo_kolla_template_overrides.j2"
      {% else -%}
       "{{ openstack_git_root }}/tripleo-common/container-images/tripleo_kolla_template_overrides.j2"
      {% endif %}
