---
# zuul.d/base.yaml
# This file contains parent layouts for all TripleO jobs.
# Do not add children specific layout here.

- job:
    name: tripleo-ci-base
    abstract: true
    description: |
        Base abstract job for all TripleO CI zuulv3 jobs
    parent: multinode
    timeout: 10800
    post-timeout: 3600
    vars:
      unbound_cache_min_ttl: 900
      ara_generate_html: true
      bridge_name: br-ex
      bridge_address_prefix: 192.168.24
      bridge_address_subnet: 24
      bridge_address_offset: 2
      bridge_mtu: 1350
    nodeset: two-centos-7-nodes
    roles:
      - zuul: git.openstack.org/openstack-infra/zuul-jobs
      - zuul: git.openstack.org/openstack-infra/openstack-zuul-jobs
    required-projects:
      - git.openstack.org/openstack-infra/tripleo-ci
      - git.openstack.org/openstack/tripleo-quickstart
      - git.openstack.org/openstack/tripleo-quickstart-extras
      - git.openstack.org/openstack/tripleo-upgrade
      - git.openstack.org/openstack/browbeat
      - git.openstack.org/openstack/tripleo-ha-utils
    pre-run:
      - playbooks/nodepool-provider/pre.yaml
      - playbooks/openstack-zuul-jobs/legacy/pre.yaml
      - playbooks/tripleo-ci/ceph.yaml
      - playbooks/tripleo-ci/pre.yaml
    run: playbooks/tripleo-ci/run-v3.yaml
    post-run: playbooks/tripleo-ci/post.yaml
    irrelevant-files:
      - ^.*\.md$
      - ^.*\.rst$
      - ^doc/.*$
      - ^etc/.*$
      - ^metadata.json$
      - ^releasenotes/.*$
      - ^requirements.txt$
      - ^test-requirements.txt$
      - ^spec/.*$
      - ^Puppetfile.*$
      - tox.ini
      - ^setup.*$

- job:
    name: tripleo-ci-base-multinode
    abstract: true
    description: |
        Base abstract job for multinode TripleO CI zuulv3 jobs
    parent: tripleo-ci-base
    vars:
      undercloud: 127.0.0.2
      environment_infra: osinfra
      environment_type: multinode
      common_featureset: featureset-multinode-common.yml
      playbooks:
        - quickstart.yml
        - multinode-undercloud.yml
        - multinode-overcloud-prep.yml
        - multinode-overcloud.yml
        - multinode-overcloud-update.yml
        - multinode-overcloud-upgrade.yml
        - multinode-validate.yml
      tags:
        - build
        - undercloud-setup
        - undercloud-scripts
        - undercloud-install
        - undercloud-post-install
        - tripleo-validations
        - overcloud-scripts
        - overcloud-prep-config
        - overcloud-prep-containers
        - overcloud-deploy
        - overcloud-post-deploy
        - overcloud-validate

- job:
    name: tripleo-ci-base-ovb
    abstract: true
    description: |
        Base abstract job for OVB TripleO CI zuulv3 jobs
    parent: tripleo-ci-base
    nodeset: single-centos-7-node
    vars:
      undercloud: undercloud
      environment_infra: ovb
      environment_type: ovb
      playbooks:
        - ovb-setup.yml
        - baremetal-full-undercloud.yml
        - baremetal-full-overcloud-prep.yml
        - baremetal-full-overcloud.yml
        - baremetal-full-overcloud-validate.yml
      tags:
        - all

- job:
    name: tripleo-ci-base-singlenode
    abstract: true
    description: |
        Base abstract job for singlenode TripleO CI zuulv3 jobs
    parent: tripleo-ci-base
    nodeset: single-centos-7-node
    vars:
      undercloud: 127.0.0.2
      environment_infra: osinfra
      environment_type: singlenode
      common_featureset: featureset-multinode-common.yml
      playbooks:
        - quickstart.yml
        - multinode-undercloud.yml
        - multinode-undercloud-upgrade.yml
        - multinode-overcloud-prep.yml
        - multinode-overcloud.yml
        - multinode-overcloud-upgrade.yml
        - multinode-validate.yml
      tags:
        - build
        - undercloud-setup
        - undercloud-scripts
        - undercloud-install
        - undercloud-validate
        - images

- job:
    name: tripleo-ci-base-standalone
    abstract: true
    description: |
        Base abstract job for standalone TripleO CI zuulv3 jobs
    parent: tripleo-ci-base
    nodeset: single-centos-7-node
    vars:
      undercloud: 127.0.0.2
      environment_infra: osinfra
      environment_type: standalone
      common_featureset: featureset-multinode-common.yml
      playbooks:
        - quickstart.yml
        - multinode-standalone.yml
      tags:
        - build
        - standalone
