---
push_registry_port: 8787
push_registry: "127.0.0.1:{{ push_registry_port }}"
push_containers: "false"
kolla_base: "{{ ansible_distribution|lower }}"
kolla_base_image: "{{ kolla_base }}"
# DO NOT define a default for kolla_base_tag,
# this is here to notify of its availability as a parameter
# Kolla sets the default kolla tag on its own based on dstro
# and setting a different default breaks other distro dependent
# default (like the package manager)
# kolla_base_tag: latest
kolla_base_pull: true
use_buildah: false
buildcontainers_override_repos: ""
buildcontainers_rpm_setup_config: "http://{{ ansible_default_ipv4.address }}/delorean.repo,http://{{ ansible_default_ipv4.address }}/delorean-{{ ci_branch }}-testing.repo"
buildcontainers_venv: true
openstack_repo_name: delorean
container_cli_opt: ""
# component_ci_containers used by component-ci jobs to build e.g. nova only
# used together with component_ci_configs in vars/main
component_ci_containers: ""
openstack_git_root: "{{ ansible_user_dir }}/src/opendev.org/openstack"
# container prefix is generally centos for usptream and rhel for downstream
container_name_prefix: >-
  {% if osp_branch is not defined and ci_branch in ['train'] -%}
  {{ ansible_distribution|lower }}-binary
  {%- else -%}
  openstack
  {%- endif -%}
# In order to use custom auth file for pushing containers to registry
# --authfile flag is used. The default auth file is
# /run/containers/0/auth.json, It will be auto
# generated on doing sudo buildah login -u <user> -p <pass>
# --authfile <dir/auth.json> registry url
# buildcontainers_authfile_path: '/run/containers/0/auth.json'
registry_namespace: >-
  {% if osp_branch is defined -%}
  tripleo{{ osp_branch }}
  {%- else -%}
  tripleo{{ ci_branch }}
  {%- endif -%}
container_registry_image: quay.io/tripleoci/registry:2
provider_registry_port: 5001
container_exclude_distro: "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version}}"
# Extra config needs to be passed to tcib tool
# https://docs.openstack.org/tripleo-ansible/latest/roles/role-tripleo_container_image_build.html#r-o-l-e-d-e-f-a-u-l-t-s
tcib_extra_config:
  tcib_args:
    TRIPLEO_ANSIBLE_REQ: /usr/share/openstack-tripleo-common-containers/container-images/kolla/tripleo-ansible-ee/requirements.yaml
